config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :contacts
  root "home#index"
  get "home/about"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :contacts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /contacts
  def index
    @contacts = current_user.contacts.all
  end

  # GET /contacts/1
  def show
  end

  # GET /contacts/new
  def new
    @contact = current_user.contacts.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  def create
    @contact = current_user.contacts.new(contact_params)

    if @contact.save
      redirect_to @contact, notice: "Contact was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /contacts/1
  def update
    if @contact.update(contact_params)
      redirect_to @contact, notice: "Contact was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /contacts/1
  def destroy
    @contact.destroy
    redirect_to contacts_url, notice: "Contact was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = current_user.contacts.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contact_params
      params.require(:contact).permit(:first_name, :last_name, :email, :phone)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/contacts/_form.html.erb
<%= form_with(model: contact) do |form| %>
  <% if contact.errors.any? %>
    <article class="panel is-danger">
      <p class="panel-heading">
        <%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:
      </p>
      <% contact.errors.each do |error| %>
        <div class="panel-block">
          <%= error.full_message %>
        </div>
      <% end %>
    </article>
  <% end %>

  <div class="field">
    <%= form.label :first_name, class: "label" %>
    <div class="control">
      <%= form.text_field :first_name, class: "input" %>
    </div>
  </div>

  <div class="field">
    <%= form.label :last_name, class: "label" %>
    <div class="control">
      <%= form.text_field :last_name, class: "input" %>
    </div>
  </div>
  
  <div class="field">
    <%= form.label :email, class: "label" %>
    <div class="control">
      <%= form.text_field :email, class: "input" %>
    </div>
  </div>
  
  <div class="field">
    <%= form.label :phone, class: "label" %>
    <div class="control">
      <%= form.text_field :phone, class: "input" %>
    </div>
  </div>
  
  
  <div class="field is-grouped">
    <div class="control">
      <%= form.button class: "button is-success is-light" do %>
        <% if action_name == "new" %>
          <span class="icon">
            <span class="material-symbols-outlined">add</span>
          </span>
          <span>Create</span>
        <% else %>
          <span class="icon">
            <span class="material-symbols-outlined">edit</span>
          </span>
          <span>Update</span>
        <% end %>
      <% end %>
    </div>
    <div class="control">
      <%= link_to :back, class: "button is-danger is-light" do %>
        <span class="icon">
          <span class="material-symbols-outlined">close</span>
        </span>
        <span>Cancel</span>
      <% end %>
    </div>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<div class="level">
  <div class="level-left">
    <div class="level-item">
      <p class="title">Edit this contact</p>
    </div>
  </div>
</div>
<%= render "form", contact: @contact %>

app/views/contacts/index.html.erb
<div class="level">
  <div class="level-left">
    <div class="level-item">
      <p class="title">Contacts</p>
    </div>
  </div>
  <div class="level-right">
    <div class="level-item">
      <%= link_to new_contact_path, class: "button is-success is-light" do %>
        <span class="icon">
          <span class="material-symbols-outlined">add</span>
        </span>
        <span>Add contact</span>
      <% end %>
    </div>
  </div>
</div>
<% if @contacts.empty? %>
  <div class="content">
    <p>Your contacts seems to be empty at the moment. Try adding a few of them here to populate this page.</p>
  </div>
<% else %>
  <div class="table-container">
    <table class="table is-striped is-fullwidth" id="contacts">
      <thead>
        <tr>
          <th>Name</th>
          <th>Email</th>
          <th>Phone</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @contacts.each do |contact| %>
          <tr id="<%= dom_id contact %>">
            <th>
              <%= link_to "#{contact.first_name} #{contact.last_name}", contact %>
            </th>
            <td><%= contact.email %></td>
            <td><%= contact.phone %></td>
            <td>
              <%= link_to edit_contact_path(contact), class: "has-text-link" do %>
                <span class="material-symbols-outlined">edit</span>
              <% end %>
            </td>
            <td>
              <%= link_to contact, data: { turbo_method: :delete }, class: "has-text-danger" do %>
                <span class="material-symbols-outlined">delete</span>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>

app/views/contacts/new.html.erb
<div class="level">
  <div class="level-left">
    <div class="level-item">
      <p class="title">Create new contact</p>
    </div>
  </div>
</div>
<%= render "form", contact: @contact %>

app/views/contacts/show.html.erb
<div class="level">
  <div class="level-left">
    <div class="level-item">
      <p class="title">Details</p>
    </div>
  </div>
</div>
<div class="card">
  <div class="card-content">
    <div class="level">
      <div class="level-left">
        <div class="level-item">
          <div class="media">
            <div class="media-content">
              <strong class="is-size-2"><%= @contact.first_name %>&nbsp;<%= @contact.last_name %></strong>
            </div>
          </div>
        </div>
      </div>
      <div class="level-right">
        <div class="level-item">
          <div class="field is-grouped">
            <div class="control">
              <%= link_to edit_contact_path(@contact), class: "button is-success is-light" do %>
                <span class="icon">
                  <span class="material-symbols-outlined">edit</span>
                </span>
                <span>Edit</span>
              <% end %>
            </div>
            <div class="control">
              <%= link_to contact_path, data: { turbo_method: :delete }, class: "button is-danger is-light" do %>
                <span class="icon">
                  <span class="material-symbols-outlined">delete</span>
                </span>
                <span>Delete</span>
              <% end %>
            </div>
            <div class="control">
              <%= link_to contacts_path, class: "button is-link is-light" do %>
                <span class="icon">
                  <span class="material-symbols-outlined">arrow_back</span>
                </span>
                <span>Go back</span>
              <% end %>
            </div>

          </div>
        </div>
      </div>
    </div>
    <div class="content">
      <div class="level">
        <div class="level-item has-text-centered">
          <div>
            <p class="heading">
              <span class="material-symbols-outlined">mail</span>
            </p>
            <p class="subtitle is-5"><%= @contact.email %></p>
          </div>
        </div>
        <div class="level-item has-text-centered">
          <div>
            <p class="heading">
              <span class="material-symbols-outlined">phone</span>
            </p>
            <p class="subtitle is-5"><%= @contact.phone %></p>
          </div>
        </div>
        <div class="level-item has-text-centered">
          <div>
            <p class="heading">
              <span class="material-symbols-outlined">timeline</span>
            </p>
            <p class="subtitle is-5">
              Added <%= time_ago_in_words(@contact.created_at) %> ago
            </p>
          </div>
        </div>
      </div> 
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="level">
  <div class="level-left">
    <div class="level-item">
      <p class="title">About</p>
    </div>
  </div>
</div>
<div class="content">
  <p>A simple contact management system with user management and CRUD operation support.</p>
  <p>Libraries and frameworks used to build this project:</p>
  <div class="field is-grouped is-grouped-multiline">
    <div class="control">
      <span class="tag is-danger is-light">Rails</span>
    </div>
    <div class="control">
      <span class="tag is-info is-light">Devise</span>
    </div>
    <div class="control">
      <span class="tag is-success is-light">Propshaft</span>
    </div>
    <div class="control">
      <span class="tag is-info is-light">Turbo</span>
    </div>
    <div class="control">
      <span class="tag is-primary is-light">Stimulus</span>
    </div>
    <div class="control">
      <span class="tag is-warning is-light">JS Bundling</span>
    </div>
    <div class="control">
      <span class="tag is-info is-light">CSS Bundling</span>
    </div>
    <div class="control">
      <span class="tag is-link is-light">ActionView</span>
    </div>
    <div class="control">
      <span class="tag is-danger is-light">ActiveRecord</span>
    </div>
    <div class="control">
      <span class="tag is-link is-light">ActionMailer</span>
    </div>
    <div class="control">
      <span class="tag is-warning is-light">esbuild</span>
    </div>
    <div class="control">
      <span class="tag is-danger is-light">Sass</span>
    </div>
    <div class="control">
      <span class="tag is-primary is-light">Bulma</span>
    </div>
    <div class="control">
      <span class="tag is-success is-light">Material Symbols</span>
    </div>
    <div class="control">
      <span class="tag is-info is-light">PostgreSQL</span>
    </div>
  </div>
  <p>To start using the app, you can either register a new account, or login using an existing account.</p>
  <p>Already logged in? Start managing your contacts <%= link_to "here", contacts_path %>.</p>
</div>

app/views/layouts/_alert.html.erb
<% if alert %>
  <div class="notification is-warning is-light"> 
    <button class="delete"></button>
    <p class="alert"><%= alert %></p>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar" role="navigTestation" aria-label="main navigation">
  <div class="navbar-brand">
    <%= link_to root_path, class: "navbar-item has-text-link" do %>
      <span class="material-symbols-outlined">menu_book</span>&nbsp;<h1 class="title is-6">Phonebook</h1>
    <% end %>

    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <%= link_to "Contacts", contacts_path, class: "navbar-item" %>
    </div>
    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <% unless user_signed_in? %>
            <%= link_to new_user_registration_path, class: "button is-success is-light" do %>
              <span class="icon">
                <span class="material-symbols-outlined">person_add</span>
              </span>
              <span>Register</span>
            <% end %>
            <%= link_to new_user_session_path, class: "button is-info is-light" do %>
              <span class="icon">
                <span class="material-symbols-outlined">login</span>
              </span>
              <span>Login</span>
            <% end %>
          <% else %>
            <%= link_to edit_user_registration_path, class: "button is-warning is-light" do %>
              <span class="icon">
                <span class="material-symbols-outlined">settings</span>
              </span>
              <span>Settings</span>
            <% end %>
            <%= link_to destroy_user_session_path, class: "button is-danger is-light", data: { turbo_method: :delete } do %>
              <span class="icon">
                <span class="material-symbols-outlined">logout</span>
              </span>
              <span>Logout</span>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/_notice.html.erb
<% if notice %>
  <div class="notification is-success is-light"> 
    <button class="delete"></button>
    <p class="notice"><%= notice %></p>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Phonebook</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= favicon_link_tag asset_path('svg-400/outlined/menu_book.svg') %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <section class="section">
        <%= render "layouts/alert" %>
        <%= yield %>
      </section>
    </div>
  </body>
</html>